name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v7
            - name: Welcome Message
              run: echo "My first workflow action"

            - name: List files
              run: ls
              
            - name: View readme file
              run: cat README.md