name: Multiple Jobs Workflow

on: push

jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v7
            - name: Building the project
              run: echo "Building the project..."
            - name: Install cowsay
              run: sudo apt-get install -y cowsay
            - name: Generate ASCII Art
              run: cowsay -f dragon "Dragon says cow cow" > dragon.txt
            - name: Upload ASCII Art as Artifact
              uses: actions/upload-artifact@v7
              with:
                name: dragon-artifact
                path: dragon.txt
    Test-job:
        needs: build-job
        runs-on: ubuntu-latest
        steps:
            - name: Test File Exists
              run: grep -i "dragon" dragon.txt
            - name: Download ASCII Art Artifact
              uses: actions/download-artifact@v7
              with:
                name: dragon-artifact
    deploy-job:
        needs: Test-job
        runs-on: ubuntu-latest
        steps:
            - name: Download ASCII Art Artifact
              uses: actions/download-artifact@v7
              with:
                name: dragon-artifact
            - name: Read file
              run: cat dragon.txt
            - name: Checkout Repo Files
              run: ls -ltra

